title: Journal of Microbial Analytics
markdown: kramdown
theme: minima

# Project site settings
baseurl: "/Journal-of-Microbial-Analytics"    # <-- your repo name
url: "https://EastmoorPress.github.io"       # <-- your GitHub username

collections:
  articles:
    output: true
